In [1]:
from table_creator import *
import datetime
import pandas as pd

In [21]:
print(len([30, 30, 35, 28, 28, 28, 180, 120, 140, 180, 180, 180, 180, 180, 180, 200, 200, 17, 45, 45, 120,
                       70, 70, 10]))

24

### Product

In [23]:
# Product
"""
Contains product card with product release date, weight, max expiration time in days and multiplyer quantity 
for business to business orders
"""

cols = ['id', 'product_name', 'created_at', 'weight', 'expiration', 'number_of_items_btb']
data = {'id': list(range(1, 25)),
        'product_name': ['camembert_150', 'camembert_250', 'camembert_formaggio', 'brie_150', 'brie_300',
                         'brie_with_mint', 'roquefort', 'blue_cheese', 'red_cheese', 'cheddar_1_kg', 'cheddar_200_g', 'maasdam_1_kg',
                         'maasdam_200_g', 'gouda_1_kg', 'gouda_400_g', 'parmesan_1_kg', 'parmesan_150_g', 'ricotta',
                         'young_cheese_800_g', 'young_cheese_400_g', 'feta', 'set_1', 'set_2', 'cottage_cheese_1_kg'],
        'created_at': ['2021-08-08', '2021-08-08', '2022-05-01', '2021-08-08', '2021-09-01', '2021-08-08', '2021-08-08',
                       '2021-11-01', '2022-03-18', '2021-08-08', '2021-09-15', '2021-08-08', '2021-08-08', '2021-08-08',
                       '2021-08-08', '2021-08-08', '2021-08-08', '2022-10-08', '2023-02-01', '2023-02-01', '2021-08-08',
                       '2022-11-01', '2023-01-15', '2023-02-01'],
        'weight': [150, 250, 240, 150, 300, 250, 400, 300, 350, 1000, 200, 1000, 200, 1000, 400, 1000, 150, 250, 800,
                   400, 400, 1200, 1100, 1000],
        'expiration': [30, 30, 35, 28, 28, 28, 180, 120, 140, 180, 180, 180, 180, 180, 180, 200, 200, 17, 45, 45, 120,
                       70, 70, 10],
        'quantity_btb': [0, 6, 6, 0, 6, 6, 2, 2, 2, 1, 0, 1, 0, 1, 0, 1, 0, 10, 1, 0, 3, 1, 1, 1]
        }

df_product = pd.DataFrame(data=data)
df_product

,id,product_name,created_at,weight,expiration,quantity_btb
0,1,camembert_150,2021-08-08,150,30,0
1,2,camembert_250,2021-08-08,250,30,6
2,3,camembert_formaggio,2022-05-01,240,35,6
3,4,brie_150,2021-08-08,150,28,0
4,5,brie_300,2021-09-01,300,28,6
5,6,brie_with_mint,2021-08-08,250,28,6
6,7,roquefort,2021-08-08,400,180,2
7,8,blue_cheese,2021-11-01,300,120,2
8,9,red_cheese,2022-03-18,350,140,2
9,10,cheddar_1_kg,2021-08-08,1000,180,1
10,11,cheddar_200_g,2021-09-15,200,180,0
11,12,maasdam_1_kg,2021-08-08,1000,180,1
12,13,maasdam_200_g,2021-08-08,200,180,0
13,14,gouda_1_kg,2021-08-08,1000,180,1
14,15,gouda_400_g,2021-08-08,400,180,0
15,16,parmesan_1_kg,2021-08-08,1000,200,1
16,17,parmesan_150_g,2021-08-08,150,200,0
17,18,ricotta,2022-10-08,250,17,10
18,19,young_cheese_800_g,2023-02-01,800,45,1
19,20,young_cheese_400_g,2023-02-01,400,45,0
20,21,feta,2021-08-08,400,120,3
21,22,set_1,2022-11-01,1200,70,1
22,23,set_2,2023-01-15,1100,70,1
23,24,cottage_cheese_1_kg,2023-02-01,1000,10,1

In [16]:
# Test use case. Create a ramdomized data for 700 days
# Set up prerequisites

columns = ['category', 'amount', 'leftover' 'sale_date']
column_types = ['object', 'int64', 'float64', 'datetime64[ns]']  # not needed in new version

# Generate an empty dataset with 1000 rows
# dataset = dataset_generator(columns, column_types, 1000)

# Create empty dataset
df = create_dataframe(columns=columns)

# Day count
days = 700
today = datetime.date.today()

min_date = today - datetime.timedelta(days=days)
# min_date = date(year=2021, month=6, day=1)
min_date_format = min_date.strftime("%Y-%m-%d")
max_date = min_date + timedelta(days=days)
max_date_format = max_date.strftime("%Y-%m-%d")
print(f'The min date is {min_date}')
print(f'The max date is {max_date}')

# min_date = '2023-01-01'
# max_date = '2023-06-26'

# Fill the dataset with values using the randomizer function
df['category'] = randomizer('object', days, 'milk')
df['amount'] = randomizer('int64', days, 11, 29, 1)
df['leftover'] = randomizer('float', days, 0.1, 0.2)
df['sale_date'] = randomizer('datetime64[ns]', days, min_date_format, max_date_format)

df['id'] = df.index

# Check our df and save it in appropriate format
print(df.info())
df.to_excel('categories.xlsx', index=False)

The min date is 2021-08-08
The max date is 2023-07-09
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   category           700 non-null    object
 1   amount             700 non-null    int64
 2   leftoversale_date  0 non-null      object
 3   leftover           700 non-null    float64
 4   sale_date          700 non-null    datetime64[ns]
 5   id                 700 non-null    int64
dtypes: datetime64[ns](1), float64(1), int64(2), object(2)
memory usage: 32.9+ KB
None

### wh_1, BTB

### Orders, btb

In [25]:
# product_name = ['camembert_150', 'camembert_250', 'camembert_formaggio', 'brie_150', 'brie_300', 'brie_with_mint',
#                  'roquefort', 'blue_cheese', 'red_cheese', 'cheddar_1_kg', 'cheddar_200_g', 'maasdam_1_kg',
#                  'maasdam_200_g', 'gouda_1_kg', 'gouda_400_g', 'parmesan_1_kg', 'parmesan_150_g', 'ricotta',
#                  'young_cheese_800_g',
#                  'young_cheese_400_g', 'feta', 'set_1', 'set_2', 'cottage_cheese_1_kg']

# for product in product_name:
#     print(product)
df_product[df_product['quantity_btb'] > 0]

,id,product_name,created_at,weight,expiration,quantity_btb
1,2,camembert_250,2021-08-08,250,30,6
2,3,camembert_formaggio,2022-05-01,240,35,6
4,5,brie_300,2021-09-01,300,28,6
5,6,brie_with_mint,2021-08-08,250,28,6
6,7,roquefort,2021-08-08,400,180,2
7,8,blue_cheese,2021-11-01,300,120,2
8,9,red_cheese,2022-03-18,350,140,2
9,10,cheddar_1_kg,2021-08-08,1000,180,1
11,12,maasdam_1_kg,2021-08-08,1000,180,1
13,14,gouda_1_kg,2021-08-08,1000,180,1
15,16,parmesan_1_kg,2021-08-08,1000,200,1
17,18,ricotta,2022-10-08,250,17,10
18,19,young_cheese_800_g,2023-02-01,800,45,1
20,21,feta,2021-08-08,400,120,3
21,22,set_1,2022-11-01,1200,70,1
22,23,set_2,2023-01-15,1100,70,1
23,24,cottage_cheese_1_kg,2023-02-01,1000,10,1

In [42]:

# First let's generate item sales data using our rudimentary but simple randomizer tool
# We need a way to link our individual item sales with orders and with warehouse stock
"""
Let's make a sales table now. It will include orders and dates
It does not imply that the Client received an order on that date - it is the date the order was created
The first df will comprise B2B orders from cafes/restaurants (Horeca) and retailers

These orders are huge in comparison to individual purchasers, yet they must meet the minimum amount per item
"""

# prerequisites
days = 700
today = datetime.date.today()
columns = ['date', 'order_id', 'warehouse', 'sku_name', 'amount']

# camembert_250
df_1 = create_dataframe(columns=columns)
# Fill the dataset with values using the randomizer function
df_1['date'] = randomizer('datetime64[ns]', days, '2021-08-08', max_date_format)
# Define how many rows should be per 1 order
max_group_size = random.randint(1, 5)  # each item in order, rows x - y
df_1['order_id'] = randomizer('order_id', days, max_group_size)
df_1['warehouse'] = 1
df_1['sku_name'] = 'camembert_250'
df_1['amount'] = randomizer('int64', days, 6, 36, 6)

# camembert_formaggio
df_2 = create_dataframe(columns=columns)
# Fill the dataset with values using the randomizer function
df_2['date'] = randomizer('datetime64[ns]', days, '2022-05-01', max_date_format)
# Define how many rows should be per 1 order
max_group_size = random.randint(1, 4)  # each item in order, rows x - y
df_2['order_id'] = randomizer('order_id', days, max_group_size)
df_2['warehouse'] = 1
df_2['sku_name'] = 'camembert_formaggio'
df_2['amount'] = randomizer('int64', days, 6, 48, 6)

# brie_300
df_3 = create_dataframe(columns=columns)
# Fill the dataset with values using the randomizer function
df_3['date'] = randomizer('datetime64[ns]', days, '2021-09-01', max_date_format)
# Define how many rows should be per 1 order
max_group_size = random.randint(1, 4)  # each item in order, rows x - y
df_3['order_id'] = randomizer('order_id', days, max_group_size)
df_3['warehouse'] = 1
df_3['sku_name'] = 'brie_300'
df_3['amount'] = randomizer('int64', days, 6, 72, 6)

# brie_with_mint
df_4 = create_dataframe(columns=columns)
# Fill the dataset with values using the randomizer function
df_4['date'] = randomizer('datetime64[ns]', days, '2021-08-08', max_date_format)
# Define how many rows should be per 1 order
max_group_size = random.randint(1, 4)  # each item in order, rows x - y
df_4['order_id'] = randomizer('order_id', days, max_group_size)
df_4['warehouse'] = 1
df_4['sku_name'] = 'brie_with_mint'
df_4['amount'] = randomizer('int64', days, 0, 24, 6)

# roquefort
df_5 = create_dataframe(columns=columns)
# Fill the dataset with values using the randomizer function
df_5['date'] = randomizer('datetime64[ns]', days, '2021-08-08', max_date_format)
# Define how many rows should be per 1 order
max_group_size = random.randint(1, 4)  # each item in order, rows x - y
df_5['order_id'] = randomizer('order_id', days, max_group_size)
df_5['warehouse'] = 1
df_5['sku_name'] = 'roquefort'
df_5['amount'] = randomizer('int64', days, 0, 2, 2)

# blue_cheese
df_6 = create_dataframe(columns=columns)
# Fill the dataset with values using the randomizer function
df_6['date'] = randomizer('datetime64[ns]', days, '2021-11-01', max_date_format)
# Define how many rows should be per 1 order
max_group_size = random.randint(1, 4)  # each item in order, rows x - y
df_6['order_id'] = randomizer('order_id', days, max_group_size)
df_6['warehouse'] = 1
df_6['sku_name'] = 'blue_cheese'
df_6['amount'] = randomizer('int64', days, 2, 12, 2)

# red_cheese
df_7 = create_dataframe(columns=columns)
# Fill the dataset with values using the randomizer function
df_7['date'] = randomizer('datetime64[ns]', days, '2022-03-18', max_date_format)
# Define how many rows should be per 1 order
df_7['order_id'] = randomizer('order_id', days, max_group_size)
df_7['warehouse'] = 1
df_7['sku_name'] = 'red_cheese'
df_7['amount'] = randomizer('int64', days, 4, 10, 2)

# cheddar_1_kg
df_8 = create_dataframe(columns=columns)
# Fill the dataset with values using the randomizer function
df_8['date'] = randomizer('datetime64[ns]', days, '2021-08-08', max_date_format)
# Define how many rows should be per 1 order
df_8['order_id'] = randomizer('order_id', days, max_group_size)
df_8['warehouse'] = 1
df_8['sku_name'] = 'cheddar_1_kg'
df_8['amount'] = randomizer('int64', days, 0, 3, 1)

# maasdam_1_kg
df_9 = create_dataframe(columns=columns)
# Fill the dataset with values using the randomizer function
df_9['date'] = randomizer('datetime64[ns]', days, '2021-08-08', max_date_format)
# Define how many rows should be per 1 order
df_9['order_id'] = randomizer('order_id', days, max_group_size)
df_9['warehouse'] = 1
df_9['sku_name'] = 'maasdam_1_kg'
df_9['amount'] = randomizer('int64', days, 0, 3, 1)

# gouda_1_kg
df_10 = create_dataframe(columns=columns)
# Fill the dataset with values using the randomizer function
df_10['date'] = randomizer('datetime64[ns]', days, '2021-08-08', max_date_format)
# Define how many rows should be per 1 order
df_10['order_id'] = randomizer('order_id', days, max_group_size)
df_10['warehouse'] = 1
df_10['sku_name'] = 'gouda_1_kg'
df_10['amount'] = randomizer('int64', days, 1, 5, 1)

# gouda_1_kg
df_10 = create_dataframe(columns=columns)
# Fill the dataset with values using the randomizer function
df_10['date'] = randomizer('datetime64[ns]', days, '2021-08-08', max_date_format)
# Define how many rows should be per 1 order
df_10['order_id'] = randomizer('order_id', days, max_group_size)
df_10['warehouse'] = 1
df_10['sku_name'] = 'gouda_1_kg'
df_10['amount'] = randomizer('int64', days, 1, 3, 1)

# gouda_1_kg
df_11 = create_dataframe(columns=columns)
# Fill the dataset with values using the randomizer function
df_11['date'] = randomizer('datetime64[ns]', days, '2021-08-08', max_date_format)
# Define how many rows should be per 1 order
df_11['order_id'] = randomizer('order_id', days, max_group_size)
df_11['warehouse'] = 1
df_11['sku_name'] = 'gouda_1_kg'
df_11['amount'] = randomizer('int64', days, 1, 3, 1)

# parmesan_1_kg
df_12 = create_dataframe(columns=columns)
# Fill the dataset with values using the randomizer function
df_12['date'] = randomizer('datetime64[ns]', days, '2021-08-08', max_date_format)
# Define how many rows should be per 1 order
df_12['order_id'] = randomizer('order_id', days, max_group_size)
df_12['warehouse'] = 1
df_12['sku_name'] = 'parmesan_1_kg'
df_12['amount'] = randomizer('int64', days, 2, 8, 1)

# ricotta
df_13 = create_dataframe(columns=columns)
# Fill the dataset with values using the randomizer function
df_13['date'] = randomizer('datetime64[ns]', days, '2022-10-08', max_date_format)
# Define how many rows should be per 1 order
df_13['order_id'] = randomizer('order_id', days, max_group_size)
df_13['warehouse'] = 1
df_13['sku_name'] = 'ricotta'
df_13['amount'] = randomizer('int64', days, 10, 50, 10)

# young_cheese_800_g
df_14 = create_dataframe(columns=columns)
# Fill the dataset with values using the randomizer function
df_14['date'] = randomizer('datetime64[ns]', days, '2023-02-01', max_date_format)
# Define how many rows should be per 1 order
df_14['order_id'] = randomizer('order_id', days, max_group_size)
df_14['warehouse'] = 1
df_14['sku_name'] = 'young_cheese_800_g'
df_14['amount'] = randomizer('int64', days, 4, 18, 1)

# feta
df_15 = create_dataframe(columns=columns)
# Fill the dataset with values using the randomizer function
df_15['date'] = randomizer('datetime64[ns]', days, '2021-08-08', max_date_format)
# Define how many rows should be per 1 order
df_15['order_id'] = randomizer('order_id', days, max_group_size)
df_15['warehouse'] = 1
df_15['sku_name'] = 'feta'
df_15['amount'] = randomizer('int64', days, 18, 42, 3)

# set_1
df_16 = create_dataframe(columns=columns)
# Fill the dataset with values using the randomizer function
df_16['date'] = randomizer('datetime64[ns]', days, '2022-11-01', max_date_format)
# Define how many rows should be per 1 order
df_16['order_id'] = randomizer('order_id', days, max_group_size)
df_16['warehouse'] = 1
df_16['sku_name'] = 'set_1'
df_16['amount'] = randomizer('int64', days, 0, 2, 1)

# set_2
df_17 = create_dataframe(columns=columns)
# Fill the dataset with values using the randomizer function
df_17['date'] = randomizer('datetime64[ns]', days, '2023-01-15', max_date_format)
# Define how many rows should be per 1 order
df_17['order_id'] = randomizer('order_id', days, max_group_size)
df_17['warehouse'] = 1
df_17['sku_name'] = 'set_2'
df_17['amount'] = randomizer('int64', days, 0, 2, 1)

# cottage_cheese_1_kg
df_17 = create_dataframe(columns=columns)
# Fill the dataset with values using the randomizer function
df_17['date'] = randomizer('datetime64[ns]', days, '2023-02-01', max_date_format)
# Define how many rows should be per 1 order
df_17['order_id'] = randomizer('order_id', days, max_group_size)
df_17['warehouse'] = 1
df_17['sku_name'] = 'cottage_cheese_1_kg'
df_17['amount'] = randomizer('int64', days, 10, 20, 1)

def create_dataframe_list(start=1, finish=2):
    dataframe_list = []
    
    for i in range(start, finish):
        df_name = f"df_{i}"
        if df_name in globals():
            dataframe_list.append(eval(df_name))
        else:
            print(f"Warning: {df_name} does not exist.")
    
    return dataframe_list

In [43]:
# Beautify oue dataset

df_btb_final = pd.concat(create_dataframe_list(start=1, finish=18))

# sort out of range dates
df_btb_final = df_btb_final[df_btb_final['date'] >= '2021-08-08']

# sort and re-create order_id
df_btb_final_1 = df_btb_final.sort_values(by=['date', 'order_id'])
max_group_size = random.randint(1, 25)
df_btb_final_1['order_id'] = randomizer('order_id', len(df_btb_final), max_group_size)

# group extra items and filter 0 values (they are needed for randomized, but have no impact on the result)
df_btb_final_1_grouped = df_btb_final_1.groupby(by=['date', 'order_id', 'warehouse', 'sku_name'], as_index=False).sum()
df_btb_final_1_grouped = df_btb_final_1_grouped[df_btb_final_1_grouped['amount'] > 0]
df_btb_final_1_grouped

,date,order_id,warehouse,sku_name,amount
0,2021-08-08,1,1,brie_with_mint,6
1,2021-08-08,1,1,camembert_250,6
2,2021-08-08,1,1,cheddar_1_kg,1
3,2021-08-08,1,1,feta,21
4,2021-08-08,1,1,gouda_1_kg,3
...,...,...,...,...,...
8949,2023-07-08,1869,1,brie_300,48
8950,2023-07-08,1869,1,brie_with_mint,18
8951,2023-07-08,1869,1,camembert_250,36
8952,2023-07-08,1869,1,feta,39
8953,2023-07-08,1869,1,maasdam_1_kg,1

In [ ]:

# Then sales for individual buyers who buy directly from our web/app

"""

"""

# prerequisites
days = 700
today = datetime.date.today()
columns = ['date', 'order_id', 'warehouse', 'sku_name', 'amount']

# camembert_150
df_0 = create_dataframe(columns=columns)
# Fill the dataset with values using the randomizer function
df_0['date'] = randomizer('datetime64[ns]', days, '2021-08-08', max_date_format)
# Define how many rows should be per 1 order
max_group_size = random.randint(1, 5)  # each item in order, rows x - y
df_0['order_id'] = randomizer('order_id', days, max_group_size)
df_0['warehouse'] = 1
df_0['sku_name'] = 'camembert_150'
df_0['amount'] = randomizer('int64', days, 0, 6, 1)

# camembert_250
df_1 = create_dataframe(columns=columns)
# Fill the dataset with values using the randomizer function
df_1['date'] = randomizer('datetime64[ns]', days, '2021-08-08', max_date_format)
# Define how many rows should be per 1 order
max_group_size = random.randint(1, 5)  # each item in order, rows x - y
df_1['order_id'] = randomizer('order_id', days, max_group_size)
df_1['warehouse'] = 1
df_1['sku_name'] = 'camembert_250'
df_1['amount'] = randomizer('int64', days, 0, 4, 1)

# camembert_formaggio
df_2 = create_dataframe(columns=columns)
# Fill the dataset with values using the randomizer function
df_2['date'] = randomizer('datetime64[ns]', days, '2022-05-01', max_date_format)
# Define how many rows should be per 1 order
max_group_size = random.randint(1, 4)  # each item in order, rows x - y
df_2['order_id'] = randomizer('order_id', days, max_group_size)
df_2['warehouse'] = 1
df_2['sku_name'] = 'camembert_formaggio'
df_2['amount'] = randomizer('int64', days, 1, 3, 1)

# brie_300
df_3 = create_dataframe(columns=columns)
# Fill the dataset with values using the randomizer function
df_3['date'] = randomizer('datetime64[ns]', days, '2021-09-01', max_date_format)
# Define how many rows should be per 1 order
max_group_size = random.randint(1, 4)  # each item in order, rows x - y
df_3['order_id'] = randomizer('order_id', days, max_group_size)
df_3['warehouse'] = 1
df_3['sku_name'] = 'brie_300'
df_3['amount'] = randomizer('int64', days, 6, 72, 6)

# brie_with_mint
df_4 = create_dataframe(columns=columns)
# Fill the dataset with values using the randomizer function
df_4['date'] = randomizer('datetime64[ns]', days, '2021-08-08', max_date_format)
# Define how many rows should be per 1 order
max_group_size = random.randint(1, 4)  # each item in order, rows x - y
df_4['order_id'] = randomizer('order_id', days, max_group_size)
df_4['warehouse'] = 1
df_4['sku_name'] = 'brie_with_mint'
df_4['amount'] = randomizer('int64', days, 0, 8, 1)

# roquefort
df_5 = create_dataframe(columns=columns)
# Fill the dataset with values using the randomizer function
df_5['date'] = randomizer('datetime64[ns]', days, '2021-08-08', max_date_format)
# Define how many rows should be per 1 order
max_group_size = random.randint(1, 4)  # each item in order, rows x - y
df_5['order_id'] = randomizer('order_id', days, max_group_size)
df_5['warehouse'] = 1
df_5['sku_name'] = 'roquefort'
df_5['amount'] = randomizer('int64', days, 0, 1, 1)

# blue_cheese
df_6 = create_dataframe(columns=columns)
# Fill the dataset with values using the randomizer function
df_6['date'] = randomizer('datetime64[ns]', days, '2021-11-01', max_date_format)
# Define how many rows should be per 1 order
max_group_size = random.randint(1, 4)  # each item in order, rows x - y
df_6['order_id'] = randomizer('order_id', days, max_group_size)
df_6['warehouse'] = 1
df_6['sku_name'] = 'blue_cheese'
df_6['amount'] = randomizer('int64', days, 0, 7, 1)

# red_cheese
df_7 = create_dataframe(columns=columns)
# Fill the dataset with values using the randomizer function
df_7['date'] = randomizer('datetime64[ns]', days, '2022-03-18', max_date_format)
# Define how many rows should be per 1 order
df_7['order_id'] = randomizer('order_id', days, max_group_size)
df_7['warehouse'] = 1
df_7['sku_name'] = 'red_cheese'
df_7['amount'] = randomizer('int64', days, 0, 7, 1)

# cheddar_1_kg
df_8 = create_dataframe(columns=columns)
# Fill the dataset with values using the randomizer function
df_8['date'] = randomizer('datetime64[ns]', days, '2021-08-08', max_date_format)
# Define how many rows should be per 1 order
df_8['order_id'] = randomizer('order_id', days, max_group_size)
df_8['warehouse'] = 1
df_8['sku_name'] = 'cheddar_1_kg'
df_8['amount'] = randomizer('int64', days, 0, 1, 1)

# maasdam_1_kg
df_9 = create_dataframe(columns=columns)
# Fill the dataset with values using the randomizer function
df_9['date'] = randomizer('datetime64[ns]', days, '2021-08-08', max_date_format)
# Define how many rows should be per 1 order
df_9['order_id'] = randomizer('order_id', days, max_group_size)
df_9['warehouse'] = 1
df_9['sku_name'] = 'maasdam_1_kg'
df_9['amount'] = randomizer('int64', days, 0, 1, 1)

# gouda_1_kg
df_10 = create_dataframe(columns=columns)
# Fill the dataset with values using the randomizer function
df_10['date'] = randomizer('datetime64[ns]', days, '2021-08-08', max_date_format)
# Define how many rows should be per 1 order
df_10['order_id'] = randomizer('order_id', days, max_group_size)
df_10['warehouse'] = 1
df_10['sku_name'] = 'gouda_1_kg'
df_10['amount'] = randomizer('int64', days, 0, 1, 1)

# gouda_1_kg
df_10 = create_dataframe(columns=columns)
# Fill the dataset with values using the randomizer function
df_10['date'] = randomizer('datetime64[ns]', days, '2021-08-08', max_date_format)
# Define how many rows should be per 1 order
df_10['order_id'] = randomizer('order_id', days, max_group_size)
df_10['warehouse'] = 1
df_10['sku_name'] = 'gouda_1_kg'
df_10['amount'] = randomizer('int64', days, 0, 1, 1)

# gouda_1_kg
df_11 = create_dataframe(columns=columns)
# Fill the dataset with values using the randomizer function
df_11['date'] = randomizer('datetime64[ns]', days, '2021-08-08', max_date_format)
# Define how many rows should be per 1 order
df_11['order_id'] = randomizer('order_id', days, max_group_size)
df_11['warehouse'] = 1
df_11['sku_name'] = 'gouda_1_kg'
df_11['amount'] = randomizer('int64', days, 1, 1, 1)

# parmesan_1_kg
df_12 = create_dataframe(columns=columns)
# Fill the dataset with values using the randomizer function
df_12['date'] = randomizer('datetime64[ns]', days, '2021-08-08', max_date_format)
# Define how many rows should be per 1 order
df_12['order_id'] = randomizer('order_id', days, max_group_size)
df_12['warehouse'] = 1
df_12['sku_name'] = 'parmesan_1_kg'
df_12['amount'] = randomizer('int64', days, 0, 1, 1)

# ricotta
df_13 = create_dataframe(columns=columns)
# Fill the dataset with values using the randomizer function
df_13['date'] = randomizer('datetime64[ns]', days, '2022-10-08', max_date_format)
# Define how many rows should be per 1 order
df_13['order_id'] = randomizer('order_id', days, max_group_size)
df_13['warehouse'] = 1
df_13['sku_name'] = 'ricotta'
df_13['amount'] = randomizer('int64', days, 3, 12, 1)

# young_cheese_800_g
df_14 = create_dataframe(columns=columns)
# Fill the dataset with values using the randomizer function
df_14['date'] = randomizer('datetime64[ns]', days, '2023-02-01', max_date_format)
# Define how many rows should be per 1 order
df_14['order_id'] = randomizer('order_id', days, max_group_size)
df_14['warehouse'] = 1
df_14['sku_name'] = 'young_cheese_800_g'
df_14['amount'] = randomizer('int64', days, 1, 7, 1)

# feta
df_15 = create_dataframe(columns=columns)
# Fill the dataset with values using the randomizer function
df_15['date'] = randomizer('datetime64[ns]', days, '2021-08-08', max_date_format)
# Define how many rows should be per 1 order
df_15['order_id'] = randomizer('order_id', days, max_group_size)
df_15['warehouse'] = 1
df_15['sku_name'] = 'feta'
df_15['amount'] = randomizer('int64', days, 3, 12, 1)

# set_1
df_16 = create_dataframe(columns=columns)
# Fill the dataset with values using the randomizer function
df_16['date'] = randomizer('datetime64[ns]', days, '2022-11-01', max_date_format)
# Define how many rows should be per 1 order
df_16['order_id'] = randomizer('order_id', days, max_group_size)
df_16['warehouse'] = 1
df_16['sku_name'] = 'set_1'
df_16['amount'] = randomizer('int64', days, 0, 1, 1)

# set_2
df_17 = create_dataframe(columns=columns)
# Fill the dataset with values using the randomizer function
df_17['date'] = randomizer('datetime64[ns]', days, '2023-01-15', max_date_format)
# Define how many rows should be per 1 order
df_17['order_id'] = randomizer('order_id', days, max_group_size)
df_17['warehouse'] = 1
df_17['sku_name'] = 'set_2'
df_17['amount'] = randomizer('int64', days, 0, 1, 1)

# cottage_cheese_1_kg
df_17 = create_dataframe(columns=columns)
# Fill the dataset with values using the randomizer function
df_17['date'] = randomizer('datetime64[ns]', days, '2023-02-01', max_date_format)
# Define how many rows should be per 1 order
df_17['order_id'] = randomizer('order_id', days, max_group_size)
df_17['warehouse'] = 1
df_17['sku_name'] = 'cottage_cheese_1_kg'
df_17['amount'] = randomizer('int64', days, 2, 15, 1)

# brie_150
df_18 = create_dataframe(columns=columns)
# Fill the dataset with values using the randomizer function
df_18['date'] = randomizer('datetime64[ns]', days, '2021-08-08', max_date_format)
# Define how many rows should be per 1 order
df_18['order_id'] = randomizer('order_id', days, max_group_size)
df_18['warehouse'] = 1
df_18['sku_name'] = 'brie_150'
df_18['amount'] = randomizer('int64', days, 1, 14, 1)

# cheddar_200_g
df_19 = create_dataframe(columns=columns)
# Fill the dataset with values using the randomizer function
df_19['date'] = randomizer('datetime64[ns]', days, '2021-09-15', max_date_format)
# Define how many rows should be per 1 order
df_19['order_id'] = randomizer('order_id', days, max_group_size)
df_19['warehouse'] = 1
df_19['sku_name'] = 'cheddar_200_g'
df_19['amount'] = randomizer('int64', days, 4, 17, 1)

# maasdam_200_g
df_20 = create_dataframe(columns=columns)
# Fill the dataset with values using the randomizer function
df_20['date'] = randomizer('datetime64[ns]', days, '2021-08-08', max_date_format)
# Define how many rows should be per 1 order
df_20['order_id'] = randomizer('order_id', days, max_group_size)
df_20['warehouse'] = 1
df_20['sku_name'] = 'maasdam_200_g'
df_20['amount'] = randomizer('int64', days, 4, 19, 1)

# parmesan_150_g
df_21 = create_dataframe(columns=columns)
# Fill the dataset with values using the randomizer function
df_21['date'] = randomizer('datetime64[ns]', days, '2021-09-15', max_date_format)
# Define how many rows should be per 1 order
df_21['order_id'] = randomizer('order_id', days, max_group_size)
df_21['warehouse'] = 1
df_21['sku_name'] = 'parmesan_150_g'
df_21['amount'] = randomizer('int64', days, 5, 18, 1)

def create_dataframe_list(start=1, finish=2):
    dataframe_list = []
    
    for i in range(start, finish):
        df_name = f"df_{i}"
        if df_name in globals():
            dataframe_list.append(eval(df_name))
        else:
            print(f"Warning: {df_name} does not exist.")
    
    return dataframe_list

In [5]:
df_2 = create_dataframe(columns=columns)
# Fill the dataset with values using the randomizer function
df_2['date'] = randomizer('datetime64[ns]', days, min_date_format, max_date_format)
# Define how many rows should be per 1 order
max_group_size = random.randint(0, 8)
df_2['order_id'] = randomizer('order_id', days, max_group_size)
df_2['warehouse'] = 1
df_2['sku_name'] = 'maasdam_farmstore_400_g'
df_2['amount'] = randomiz
er('int64', days, 1, 4, 1)
df_2.head(7)

,date,order_id,warehouse,sku_name,amount
0,2021-08-08,1,1,maasdam_farmstore_400_g,1
1,2021-08-09,1,1,maasdam_farmstore_400_g,1
2,2021-08-10,1,1,maasdam_farmstore_400_g,1
3,2021-08-11,1,1,maasdam_farmstore_400_g,4
4,2021-08-12,2,1,maasdam_farmstore_400_g,2
5,2021-08-13,2,1,maasdam_farmstore_400_g,1
6,2021-08-14,2,1,maasdam_farmstore_400_g,3

In [ ]:
# Rescale sales data by weekday. Assume that we will get more orders on Fridays, Sundays, and Saturdays 
# and fewer on the other days of the week.

In [ ]:
# Then add different flactuations to our sales - new items, cannibalisation, promotions and seasonality